name: microservice
services:
  rabbitmq:
      image: "rabbitmq:4.2.3-management"
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
          RABBITMQ_DEFAULT_USER: "fabada"
          RABBITMQ_DEFAULT_PASS: "83567"